### ISSUE TITLE
最新版撰写文章模块有问题

### ISSUE THREAD

**Issue by Respawn-ID** [XG2020/TypechoDIY#1]
安装最新版diy后撰写文章模块前几个标志变为乱码

![](https://s1.ax1x.com/2022/12/13/z5PnyD.png)

**Comment by Respawn-ID** [comment]
重装后依旧复现

**Comment by Respawn-ID** [comment]
且只在苹果系统内出现

**Comment by XG2020** [comment]
> 且只在苹果系统内出现

这可能是苹果浏览器的矢量图解析显示出了不兼容问题

**Comment by XG2020** [comment]
> 且只在苹果系统内出现

乱码部分是官方的图标，不使用美化存在这种现象吗？如果仍然存在，可能需要去官方版反馈问题

**Comment by XG2020** [comment]
> 且只在苹果系统内出现

![-7899a1fbcf012cd8](https://user-images.githubusercontent.com/65523473/207244033-81607c37-72ca-4f72-bdc7-8d5bd7be5f6f.jpg)
测试，iOS移动端显示正常

**Comment by Respawn-ID** [comment]
不使用美化也存在，之前图标正常突然就不可使用了
重启也不好使
鉴定为阿三的IPadOS16
而且safari，chrome均存在问题。。。。我都怀疑我自己是不是搞错了
